config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index', via: :get

  resources :products, only: [:index, :show]
  resources :subscriptions
  resources :subscription_items

  mount StripeEvent::Engine, at: 'stripe#webhook'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_one :subscription
end

app/models/concerns/payment_gateway.rb
class PaymentGateway
  def self.create_plan(plan)
    begin
      Stripe::Plan.create(
        :amount => plan.product.price,
        :interval => "month",
        :name => plan.product.name,
        :currency => "usd",
        :id => plan.name
      )
    rescue => e
      puts "EXCEPTION: #{e.message}"
    end
  end

  # def self.create_subscription(plan)
  #   begin
  #     Stripe::Subscription.create(
  #       :customer => current_customer.stripe_id,
  #       :items => [
  #         {
  #           :plan => "#{plan.name}",
  #         },
  #       ]
  #     )
  #   rescue => e
  #     puts "EXCEPTION: #{e.message}"
  #   end
  # end


end

app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :subscriptions
  has_many :subscription_items, through: :subscriptions
  has_many :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  belongs_to :product
  belongs_to :subscription

  after_create :create_plan_on_payment_gateway


  def create_plan_on_payment_gateway
    PaymentGateway.create_plan(self)
  end


end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :subscription_items
  has_many :plans
  belongs_to :subscription

  def image_path
    "dash_icons/#{self.category_name}/#{self.name}.jpg"
  end

  def category_name
    self.category.name
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :customer
  has_many :subscription_items
  belongs_to :category
  has_many :plans
  has_many :products, through: :subscription_items

end

app/models/subscription_item.rb
class SubscriptionItem < ActiveRecord::Base
  belongs_to :subscription
  belongs_to :product
  has_one :category, through: :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    Customer.first
  end

end

app/controllers/concerns/subscriptions_helper.rb
module SubscriptionsHelper

#subscribe to previously cancelled subscription
  def re_subscribe
    @subscription.status = 'active'
    @subscription.save
  end

#  update the subscription with new plan
  def add_plan
    @new_subscription ||= @subscribtion
    Stripe::SubscriptionItem.create(
          subscription: @new_stripe_subscription.stripe_id,
          :plan => Stripe::Plan.create(
            :amount => @product.price,
            :interval => "month",
            :name => @product.name,
            :currency => "usd"
          ).id
      )
  end

  def create_subscription
    @new_stripe_subscription = Stripe::Subscription.create(
    :customer => @current_user.stripe_id,
    :items => [
      {
        :plan => Stripe::Plan.create(
          :amount => @product.price,
          :interval => "month",
          :name => @product.name,
          :currency => "usd"
        ).id
      }
      ]
    )

    @new_subscription = Subscription.create(:stripe_id => @new_stripe_subscription.id, :customer_id => @current_user.id, :category_id => @product.category_id, :status => 'active')
  end

  def create_plan
    @plan = Plan.create(:name => @product.name, :product_id => @product.id, :subscription_id => @new_subscription.id)
  end


  def create_subscription_item
    @subscription_item = Stripe::SubscriptionItem.create(
      :subscription => @new_stripe_subscription.id,
      :plan => Stripe::Plan.create(
        :amount => @product.price,
        :interval => "month",
        :name => @product.name,
        :currency => "usd"
      ).id,
      :quantity => 1,
    )

    SubscriptionItem.create(:stripe_id => @subscription_item.id, :subscription_id => @new_stripe_subscription.id, :product_id => @product.id)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
require "json"
class OrdersController < ApplicationController
  post "/webhook" do
    event_json = JSON.parse(request.body.read)


    status 200
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_current_user

  def index
    @categories = Category.all
    @subscriptions = Subscription.all
  end

  def show
    @product = Product.find(params[:id])
  end


  private

  def set_current_user
    @current_user = current_user
  end

end

app/controllers/stripe_controller.rb
class StripeController < ApplicationController

  protect_from_forgery except: :webhook

  def webhook
    StripeEvent.configure do |events|
      events.all do |event|
        if event.type == 'invoice.payment_succeeded'
          Order.create(:stripe_id => id, :customer_id => current_user.id)
        end
      end
    end
  end



end

app/controllers/subscriptions_controller.rb
require "stripe"

class SubscriptionsController < ApplicationController
  include SubscriptionsHelper

  before_action :set_current_user

  def index
    @subscriptions = @current_user.subscriptions
    @plans = Plan.all
  end

  def create
    set_product
    set_subscription
    # create or update subscription in Stripe and database
    # Locate specific subscription
    if @subscription && @subscription.status = 'canceled'
      re_subscribe
    elsif @subscription && @subscription.status = 'active'
      add_plan
      create_plan
    else
      create_subscription
      create_plan
      create_subscription_item
    end

    redirect_to subscriptions_path
  end

  # cancel customer subscription without deleting subscription
  def destroy
    @subscription = Subscription.find(params[:id])

    @subscription.status = 'canceled'

    redirect_to subscriptions_path, notice: "Your #{@subscription.category.name} subscription has been canceled."
    @subscription.save
  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def set_subscription
    @subscription = @current_user.subscriptions.find_by(:category_id => @product.category_id)
  end

  def set_current_user
    @current_user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<br>
<%= link_to "View All Products", products_path, style: 'margin:20px;' %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyDash</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="margin:60px;">

<%= yield %>

</body>
</html>

app/views/products/_product.html.erb
<div class="products">
  <%= image_tag(product.image_path) %>

  <%= button_to "Subscribe", subscriptions_path(:method => :post, :product_id => product.id)%>

</div>

app/views/products/index.html.erb
<h3><%= "Logged in as #{@current_user.first_name}" %></h3>
<% @categories.each do |category| %>
<div class="categories">
  <h4><%= category.name.humanize %></h4>
  <% category.products.each do |product| %>
    <%= render product %>
  <% end %>
</div>
  <hr>
<% end %>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

app/views/subscription_items/index.html.erb
<% @subscription_items.each do |subscription_item| %>
  <li><%= debug subscription_item %></li>
<% end %>

app/views/subscriptions/_new.html.erb
<div class="products">
  <%= image_tag(product.image_path) %>

  <%= form_for @subscription %>
    <button type="submit">Subscribe</button>
  <% end %>



</div>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<% @subscriptions.each do |subscription| %>
  <% if subscription.status == 'active' %>
    <li>
      <%= subscription.category.name.humanize %>
      <br>
      <p> Subscribed Plans:
        <% @plans.each do |plan| %>
            <% if plan.subscription_id == subscription.id %>
              <%= plan.name %><br>
            <% end %>
        <% end %>
      </p>
      <br>
      <%= link_to 'Cancel Subscription', subscription_path(subscription), :method=>:delete %>
      <br></br>
    </li>
  <% end %>


<% end %>

<%= link_to 'Back to Products List', products_path %>